"""empty message

Revision ID: 155c116ddc1d
Revises: 
Create Date: 2019-09-11 03:28:34.075899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155c116ddc1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_user_email'), 'site_user', ['email'], unique=True)
    op.create_index(op.f('ix_site_user_username'), 'site_user', ['username'], unique=True)
    op.create_table('country',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('modify_timestamp', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['site_user.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['site_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_modify_timestamp'), 'country', ['modify_timestamp'], unique=False)
    op.create_index(op.f('ix_country_timestamp'), 'country', ['timestamp'], unique=False)
    op.create_table('language',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('modify_timestamp', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('native_name', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['site_user.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['site_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_modify_timestamp'), 'language', ['modify_timestamp'], unique=False)
    op.create_index(op.f('ix_language_timestamp'), 'language', ['timestamp'], unique=False)
    op.create_table('author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('modify_timestamp', sa.DateTime(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['site_user.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['site_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_modify_timestamp'), 'author', ['modify_timestamp'], unique=False)
    op.create_index(op.f('ix_author_timestamp'), 'author', ['timestamp'], unique=False)
    op.create_table('author_language',
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('modify_timestamp', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('date_written', sa.String(length=256), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['site_user.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['site_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_modify_timestamp'), 'post', ['modify_timestamp'], unique=False)
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_index(op.f('ix_post_modify_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('author_language')
    op.drop_index(op.f('ix_author_timestamp'), table_name='author')
    op.drop_index(op.f('ix_author_modify_timestamp'), table_name='author')
    op.drop_table('author')
    op.drop_index(op.f('ix_language_timestamp'), table_name='language')
    op.drop_index(op.f('ix_language_modify_timestamp'), table_name='language')
    op.drop_table('language')
    op.drop_index(op.f('ix_country_timestamp'), table_name='country')
    op.drop_index(op.f('ix_country_modify_timestamp'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_site_user_username'), table_name='site_user')
    op.drop_index(op.f('ix_site_user_email'), table_name='site_user')
    op.drop_table('site_user')
    # ### end Alembic commands ###
