"""empty message

Revision ID: 26be2813a671
Revises: 
Create Date: 2019-08-16 09:23:15.141917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26be2813a671'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_user_email'), 'blog_user', ['email'], unique=True)
    op.create_index(op.f('ix_blog_user_username'), 'blog_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_user_username'), table_name='blog_user')
    op.drop_index(op.f('ix_blog_user_email'), table_name='blog_user')
    op.drop_table('blog_user')
    # ### end Alembic commands ###
