"""author photo path

Revision ID: 6e8a6e51928b
Revises: 155c116ddc1d
Create Date: 2019-09-13 03:43:47.466784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8a6e51928b'
down_revision = '155c116ddc1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('photo_path', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'photo_path')
    # ### end Alembic commands ###
