"""empty message

Revision ID: fc9647c7fa3c
Revises: bad2f5dc3205
Create Date: 2019-08-16 10:09:32.490793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc9647c7fa3c'
down_revision = 'bad2f5dc3205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('blog_user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('blog_user', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('post', 'body',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('post', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('post', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post', 'body',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('blog_user', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('blog_user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('blog_user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
